### ISSUE TITLE
Works pretty well

### ISSUE THREAD

**Issue by BenM04** [2emk7/2emk7.github.io#3]
This works pretty well, the only issue I have with it is the blur and google drive function. They do not have a way to revert it as far as I can tell, so I have to close the tab and reopen it. Other than that, and also the popup browser not working, it is an awesome tool. (The popup not working may be because of GoGaurdian? not sure tho...)

**Comment by 2emk7** [comment]
i cant figure out how to undo the google drive bookmarklet, likely as the bookmarklet directly edits the html of the page, where the previous data containing the name and favicon were overridden, making it so I can't go back and pull the original (as i know). I created and added an unblur bookmarklet. 

The popup browser doesent work as I accidentally left in double quotations, which HTML doesnt like, cutting the code off early. HTML prefers &quot; instead of " inside of hyperlinked code.

I made a new and shorter code for the bing popup browser which should work.
